// ui/web/src/pages/channels/channel-fields.tsx
import { useTranslation } from "react-i18next";
import { useState } from "react";
import { Search, Loader2 } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { MultiUserPicker } from "@/components/shared/multi-user-picker";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ToolNameSelect } from "@/components/shared/tool-name-select";
import { SkillNameSelect } from "@/components/shared/skill-name-select";
import { useWs } from "@/hooks/use-ws";
import { Methods } from "@/api/protocol";
import { toast } from "@/stores/use-toast-store";
import type { FieldDef } from "./channel-schemas";

const INHERIT = "__inherit__";

interface ChannelFieldsProps {
  fields: FieldDef[];
  values: Record<string, unknown>;
  onChange: (key: string, value: unknown) => void;
  idPrefix: string;
  instanceId?: string;
  isEdit?: boolean; // for credentials: show "leave blank to keep" hint
  /** Extra values for showWhen checks (e.g. config values visible to credential fields) */
  contextValues?: Record<string, unknown>;
}

export function ChannelFields({ fields, values, onChange, idPrefix, instanceId, isEdit, contextValues }: ChannelFieldsProps) {
  const allValues = contextValues ? { ...contextValues, ...values } : values;
  return (
    <div className="grid gap-3">
      {fields.map((field) => {
        // Conditional visibility: skip field if showWhen condition is not met
        if (field.showWhen) {
          const depValue = allValues[field.showWhen.key] ?? fields.find((f) => f.key === field.showWhen!.key)?.defaultValue;
          const depStr = depValue !== undefined && depValue !== null ? String(depValue) : "";
          const match = Array.isArray(field.showWhen.value)
            ? field.showWhen.value.includes(depStr)
            : depStr === field.showWhen.value;
          if (!match) return null;
        }
        // Check disabledWhen condition
        let disabled = false;
        let disabledHint: string | undefined;
        if (field.disabledWhen) {
          const depValue = allValues[field.disabledWhen.key] ?? fields.find((f) => f.key === field.disabledWhen!.key)?.defaultValue;
          if (String(depValue) === field.disabledWhen.value) {
            disabled = true;
            disabledHint = field.disabledWhen.hint;
          }
        }
        return (
          <FieldRenderer
            key={field.key}
            field={field}
            value={values[field.key]}
            onChange={(v) => onChange(field.key, v)}
            id={`${idPrefix}-${field.key}`}
            instanceId={instanceId}
            isEdit={isEdit}
            disabled={disabled}
            disabledHint={disabledHint}
          />
        );
      })}
    </div>
  );
}

function FieldAction({ 
  field, 
  value, 
  instanceId,
  onChange 
}: { 
  field: FieldDef; 
  value: string; 
  instanceId?: string;
  onChange: (v: string) => void 
}) {
  const ws = useWs();
  const [loading, setLoading] = useState(false);

  const handleAction = async () => {
    if (!field.action || !value) return;

    if (!instanceId) {
      toast.info("Instance ID missing", "Please save the channel first before resolving ID.");
      return;
    }

    setLoading(true);
    try {
      if (field.action.type === "whatsapp_resolve_jid") {
        const res = await ws.call(Methods.WHATSAPP_ID_RESOLVE, {
          instance_id: instanceId,
          phone: value
        }) as { jid: string; lid: string };
        
        if (res.jid) {
          onChange(res.jid);
          toast.success("Identity Resolved", `JID: ${res.jid}`);
        }
      } else if (field.action.type === "whatsapp_verify_code") {
        await ws.call(Methods.PAIRING_APPROVE, {
          code: value.trim().toUpperCase(),
          approvedBy: "dashboard-owner"
        });
        
        onChange("");
        toast.success("Code Validated", "Your WhatsApp number has been successfully verified as Owner.");
      }
    } catch (err: any) {
      toast.error("Discovery Failed", err.message || String(err));
    } finally {
      setLoading(false);
    }
  };

  if (!field.action) return null;

  return (
    <Button
      type="button"
      variant="outline"
      size="sm"
      className="h-9 px-2 gap-1.5"
      onClick={handleAction}
      disabled={loading || !value}
    >
      {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Search className="h-3.5 w-3.5" />}
      <span className="hidden sm:inline text-xs">{field.action.label}</span>
    </Button>
  );
}

function FieldRenderer({
  field,
  value,
  onChange,
  id,
  instanceId,
  isEdit,
  disabled,
  disabledHint,
}: {
  field: FieldDef;
  value: unknown;
  onChange: (v: unknown) => void;
  id: string;
  instanceId?: string;
  isEdit?: boolean;
  disabled?: boolean;
  disabledHint?: string;
}) {
  const { t } = useTranslation("channels");
  // i18n: try "fieldConfig.<key>.label" / "fieldConfig.<key>.help", fall back to hardcoded schema string
  const label = t(`fieldConfig.${field.key}.label`, { defaultValue: field.label });
  const help = field.help ? t(`fieldConfig.${field.key}.help`, { defaultValue: field.help }) : "";
  const resolvedHint = disabledHint ? t(disabledHint, { defaultValue: disabledHint }) : undefined;
  const labelSuffix = field.required && !isEdit ? " *" : "";
  const editHint = isEdit && field.type === "password" ? ` ${t("form.credentialsHint")}` : "";

  switch (field.type) {
    case "text":
    case "password":
      return (
        <div className="grid gap-1.5">
          <Label htmlFor={id}>
            {label}{labelSuffix}{editHint}
          </Label>
          <div className="flex gap-2">
            <Input
              id={id}
              className="flex-1"
              type={field.type}
              value={(value as string) ?? ""}
              onChange={(e) => onChange(e.target.value)}
              placeholder={field.placeholder}
            />
            {field.action && (
              <FieldAction 
                field={field} 
                value={(value as string) ?? ""} 
                instanceId={instanceId}
                onChange={(v) => onChange(v)} 
              />
            )}
          </div>
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );

    case "number":
      return (
        <div className="grid gap-1.5">
          <Label htmlFor={id}>{label}{labelSuffix}</Label>
          <Input
            id={id}
            type="number"
            value={value !== undefined && value !== null ? String(value) : ""}
            onChange={(e) => onChange(e.target.value ? Number(e.target.value) : undefined)}
            placeholder={field.defaultValue !== undefined ? String(field.defaultValue) : undefined}
          />
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );

    case "boolean": {
      const boolHint = resolvedHint || help;
      return (
        <div className={`grid gap-1${disabled ? " opacity-50" : ""}`}>
          <div className="flex items-center gap-2">
            <Switch
              id={id}
              checked={(value as boolean) ?? (field.defaultValue as boolean) ?? false}
              onCheckedChange={(v) => onChange(v)}
              disabled={disabled}
            />
            <Label htmlFor={id}>{label}</Label>
          </div>
          {boolHint && <p className="text-xs text-muted-foreground ml-9">{boolHint}</p>}
        </div>
      );
    }

    case "select":
      return (
        <div className="grid gap-1.5">
          <Label>{label}{labelSuffix}</Label>
          <Select
            value={(value as string) ?? (field.defaultValue as string) ?? ""}
            onValueChange={(v) => onChange(v)}
          >
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {field.options?.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>
                  {t(`fieldOptions.${field.key}.${opt.value}`, { defaultValue: opt.label })}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );

    case "tristate": {
      // Tri-state: undefined = inherit, value = override.
      // With options: select with Inherit + custom options (string value).
      // Without options: select with Inherit/Yes/No (boolean value).
      const inheritLabel = t("groupOverrides.fields.inherit", { defaultValue: "Inherit" });

      if (field.options) {
        // String tri-state (e.g. group_policy)
        const allOptions = [{ value: INHERIT, label: inheritLabel }, ...field.options];
        const selectValue = (value as string) || INHERIT;
        return (
          <div className="grid gap-1.5">
            <Label>{label}</Label>
            <Select
              value={selectValue}
              onValueChange={(v) => onChange(v === INHERIT ? undefined : v)}
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {allOptions.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value}>
                    {opt.value === INHERIT ? inheritLabel : t(`fieldOptions.${field.key}.${opt.value}`, { defaultValue: opt.label })}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            {help && <p className="text-xs text-muted-foreground">{help}</p>}
          </div>
        );
      }

      // Boolean tri-state (e.g. require_mention, enabled)
      const yesLabel = t("groupOverrides.fields.yes", { defaultValue: "Yes" });
      const noLabel = t("groupOverrides.fields.no", { defaultValue: "No" });
      const triOptions = [
        { value: INHERIT, label: inheritLabel },
        { value: "true", label: yesLabel },
        { value: "false", label: noLabel },
      ];
      const boolToStr = (v: unknown): string => {
        if (v === undefined || v === null) return INHERIT;
        return v ? "true" : "false";
      };
      const strToBool = (v: string): boolean | undefined => {
        if (v === INHERIT) return undefined;
        return v === "true";
      };

      return (
        <div className={`grid gap-1.5${disabled ? " opacity-50" : ""}`}>
          <Label>{label}</Label>
          <Select value={boolToStr(value)} onValueChange={(v) => onChange(strToBool(v))} disabled={disabled}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {triOptions.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>{opt.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          {resolvedHint && <p className="text-xs text-muted-foreground">{resolvedHint}</p>}
          {!resolvedHint && help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );
    }

    case "textarea":
      return (
        <div className="grid gap-1.5">
          <Label htmlFor={id}>{label}</Label>
          <Textarea
            id={id}
            value={(value as string) ?? ""}
            onChange={(e) => onChange(e.target.value || undefined)}
            placeholder={field.placeholder}
            rows={3}
          />
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );

    case "tool-select":
      return (
        <div className="grid gap-1.5">
          <Label>{label}</Label>
          <ToolNameSelect
            value={(value as string[]) ?? []}
            onChange={(v) => onChange(v.length > 0 ? v : undefined)}
            placeholder={field.placeholder}
          />
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );

    case "skill-select":
      return (
        <div className="grid gap-1.5">
          <Label>{label}</Label>
          <SkillNameSelect
            value={(value as string[]) ?? []}
            onChange={(v) => onChange(v.length > 0 ? v : undefined)}
            placeholder={field.placeholder}
          />
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );

    case "tags":
      return (
        <div className="grid gap-1.5">
          <Label htmlFor={id}>{label}</Label>
          <MultiUserPicker
            value={(value as string[]) ?? []}
            onChange={(v) => onChange(v)}
            placeholder={field.placeholder ?? t("groupOverrides.fields.allowedUsersPlaceholder")}
          />
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
        </div>
      );

    default:
      return null;
  }
}

// ui/svelte-v2/src/pages/channels/components/ChannelFields.svelte
<script lang="ts">
  import { _ } from "svelte-i18n";
  import { Search, Loader2, X } from "lucide-svelte";
  import type { FieldDef } from "../channel-schemas";
  import { useWs } from "$lib/state/ws.svelte";
  import { Methods } from "$lib/api/protocol";
  // Assuming a toast store exists or just using console for now if not sure, 
  // but let's try to match the project's feedback mechanism if found.
  // In ChannelDetail.svelte it uses alert/confirm, so I'll stick to that or basic feedback.

  type Props = {
    fields: FieldDef[];
    values: Record<string, any>;
    onChange: (key: string, value: any) => void;
    idPrefix: string;
    instanceId?: string;
    isEdit?: boolean;
    contextValues?: Record<string, any>;
  };

  let { 
    fields, 
    values, 
    onChange, 
    idPrefix, 
    instanceId, 
    isEdit = false, 
    contextValues = {} 
  }: Props = $props();

  let allValues = $derived({ ...contextValues, ...values });

  function isFieldVisible(field: FieldDef) {
    if (!field.showWhen) return true;
    
    const depValue = allValues[field.showWhen.key] ?? fields.find(f => f.key === field.showWhen!.key)?.defaultValue;
    const depStr = depValue !== undefined && depValue !== null ? String(depValue) : "";
    
    if (Array.isArray(field.showWhen.value)) {
      return field.showWhen.value.includes(depStr);
    }
    return depStr === field.showWhen.value;
  }

  function isFieldDisabled(field: FieldDef) {
    if (!field.disabledWhen) return false;
    
    const depValue = allValues[field.disabledWhen.key] ?? fields.find(f => f.key === field.disabledWhen!.key)?.defaultValue;
    return String(depValue) === field.disabledWhen.value;
  }

  // Action handling
  let actionLoading = $state<Record<string, boolean>>({});

  async function handleAction(field: FieldDef, value: string) {
    if (!field.action || !value || !instanceId) return;

    actionLoading[field.key] = true;
    const ws = useWs();

    try {
      if (field.action.type === "whatsapp_resolve_jid") {
        const res = await ws.call(Methods.WHATSAPP_ID_RESOLVE, {
          instance_id: instanceId,
          phone: value
        }) as { jid: string; lid: string };
        
        if (res.jid) {
          onChange(field.key, res.jid);
          alert(`Identity Resolved: ${res.jid}`);
        }
      } else if (field.action.type === "whatsapp_verify_code") {
        await ws.call(Methods.PAIRING_APPROVE, {
          code: value.trim().toUpperCase(),
          approvedBy: "dashboard-owner"
        });
        
        onChange(field.key, "");
        alert("Code Validated successfully.");
      }
    } catch (err: any) {
      alert(`Action Failed: ${err.message || String(err)}`);
    } finally {
      actionLoading[field.key] = false;
    }
  }
</script>

<div class="grid gap-6">
  {#each fields as field (field.key)}
    {#if isFieldVisible(field)}
      {@const disabled = isFieldDisabled(field)}
      {@const id = `${idPrefix}-${field.key}`}
      {@const label = $_(`channels:fieldConfig.${field.key}.label`, { default: field.label })}
      {@const help = field.help ? $_(`channels:fieldConfig.${field.key}.help`, { default: field.help }) : ""}
      {@const disabledHint = field.disabledWhen?.hint ? $_(`channels:${field.disabledWhen.hint}`, { default: field.disabledWhen.hint }) : ""}
      
      <div class={`grid gap-2 ${disabled ? 'opacity-50 pointer-events-none' : ''}`}>
        <div class="flex items-center justify-between ml-1">
          <label for={id} class="text-[10px] font-black text-white/30 uppercase tracking-[0.2em]">
            {label}
            {#if field.required && !isEdit}
              <span class="text-red-500/50 ml-0.5">*</span>
            {/if}
            {#if isEdit && field.type === 'password'}
              <span class="text-blue-400/50 normal-case font-medium tracking-normal ml-1">
                ({$_('channels.form.credentialsHint', { default: 'leave blank to keep' })})
              </span>
            {/if}
          </label>
        </div>

        {#if field.type === 'text' || field.type === 'password'}
          <div class="flex gap-2">
            <input 
              {id}
              type={field.type}
              value={values[field.key] ?? ""}
              oninput={(e) => onChange(field.key, e.currentTarget.value)}
              placeholder={field.placeholder}
              class="flex-1 bg-[#030014] border border-white/10 rounded-xl px-4 py-3 text-sm focus:border-goclaw-neon-purple focus:ring-1 focus:ring-goclaw-neon-purple/30 transition-all outline-none text-white placeholder:text-white/10"
            />
            {#if field.action}
              <button
                type="button"
                onclick={() => handleAction(field, values[field.key] ?? "")}
                disabled={actionLoading[field.key] || !values[field.key]}
                class="flex items-center gap-2 px-4 py-2 text-[10px] font-black uppercase tracking-widest rounded-xl border border-white/10 text-white/60 hover:text-white hover:bg-white/5 transition-all disabled:opacity-50"
              >
                {#if actionLoading[field.key]}
                  <Loader2 class="w-3.5 h-3.5 animate-spin" />
                {:else}
                  <Search class="w-3.5 h-3.5 text-goclaw-neon-cyan" />
                {/if}
                <span class="hidden sm:inline">{field.action.label}</span>
              </button>
            {/if}
          </div>

        {:else if field.type === 'number'}
          <input 
            {id}
            type="number"
            value={values[field.key] ?? ""}
            oninput={(e) => onChange(field.key, e.currentTarget.value ? Number(e.currentTarget.value) : undefined)}
            placeholder={field.defaultValue !== undefined ? String(field.defaultValue) : undefined}
            class="w-full bg-[#030014] border border-white/10 rounded-xl px-4 py-3 text-sm focus:border-goclaw-neon-purple transition-all outline-none text-white"
          />

        {:else if field.type === 'boolean'}
          <div class="flex items-center justify-between p-4 rounded-xl bg-white/[0.02] border border-white/5">
            <span class="text-xs font-bold text-white/80">{label}</span>
            <button 
              onclick={() => onChange(field.key, !(values[field.key] ?? field.defaultValue ?? false))}
              class={`relative w-12 h-6 rounded-full transition-all duration-500 border ${(values[field.key] ?? field.defaultValue ?? false) ? 'bg-goclaw-neon-purple/20 border-goclaw-neon-purple/40' : 'bg-white/5 border-white/10'}`}
            >
              <div class={`absolute top-1 w-4 h-4 rounded-full transition-all duration-500 ${(values[field.key] ?? field.defaultValue ?? false) ? 'left-7 bg-goclaw-neon-purple shadow-[0_0_10px_rgba(217,70,239,0.8)]' : 'left-1 bg-white/20'}`}></div>
            </button>
          </div>

        {:else if field.type === 'select'}
          <select 
            {id}
            value={values[field.key] ?? field.defaultValue ?? ""}
            onchange={(e) => onChange(field.key, e.currentTarget.value)}
            class="w-full bg-[#030014] border border-white/10 rounded-xl px-4 py-3 text-sm focus:border-goclaw-neon-purple transition-all outline-none text-white appearance-none"
          >
            {#each (field.options || []) as opt}
              <option value={opt.value}>
                {$_(`channels:fieldOptions.${field.key}.${opt.value}`, { default: opt.label })}
              </option>
            {/each}
          </select>

        {:else if field.type === 'textarea'}
          <textarea 
            {id}
            value={values[field.key] ?? ""}
            oninput={(e) => onChange(field.key, e.currentTarget.value || undefined)}
            placeholder={field.placeholder}
            rows="3"
            class="w-full bg-[#030014] border border-white/10 rounded-xl px-4 py-3 text-sm focus:border-goclaw-neon-purple transition-all outline-none text-white placeholder:text-white/10"
          ></textarea>

        {:else if field.type === 'tags' || field.type === 'tool-select' || field.type === 'skill-select'}
          {@const tags = Array.isArray(values[field.key]) ? values[field.key] : []}
          <div class="space-y-2">
            <div class="flex flex-wrap gap-2 p-3 bg-[#030014] border border-white/10 rounded-xl min-h-[46px]">
              {#each tags as tag, i}
                <span class="inline-flex items-center gap-1.5 px-2 py-1 bg-white/5 border border-white/10 rounded-lg text-xs text-white/80">
                  {tag}
                  <button 
                    onclick={() => onChange(field.key, tags.filter((_, index) => index !== i))}
                    class="p-0.5 hover:bg-white/10 rounded-md transition-colors"
                  >
                    <X class="w-3 h-3" />
                  </button>
                </span>
              {/each}
              <input 
                type="text"
                placeholder={tags.length === 0 ? (field.placeholder || "Type and press enter...") : ""}
                class="flex-1 bg-transparent border-none outline-none text-sm text-white min-w-[120px]"
                onkeydown={(e) => {
                  if (e.key === 'Enter' || e.key === ',') {
                    e.preventDefault();
                    const val = e.currentTarget.value.trim().replace(/,$/, "");
                    if (val && !tags.includes(val)) {
                      onChange(field.key, [...tags, val]);
                      e.currentTarget.value = "";
                    }
                  } else if (e.key === 'Backspace' && !e.currentTarget.value && tags.length > 0) {
                    onChange(field.key, tags.slice(0, -1));
                  }
                }}
              />
            </div>
          </div>

        {:else if field.type === 'tristate'}
          {@const currentVal = values[field.key]}
          <select 
            {id}
            value={currentVal === undefined ? "__inherit__" : String(currentVal)}
            onchange={(e) => {
              const val = e.currentTarget.value;
              if (val === "__inherit__") onChange(field.key, undefined);
              else if (val === "true") onChange(field.key, true);
              else if (val === "false") onChange(field.key, false);
              else onChange(field.key, val);
            }}
            class="w-full bg-[#030014] border border-white/10 rounded-xl px-4 py-3 text-sm focus:border-goclaw-neon-purple transition-all outline-none text-white appearance-none"
          >
            <option value="__inherit__">Inherit from system</option>
            {#if field.options}
              {#each field.options as opt}
                <option value={opt.value}>
                  {$_(`channels:fieldOptions.${field.key}.${opt.value}`, { default: opt.label })}
                </option>
              {/each}
            {:else}
              <option value="true">Yes</option>
              <option value="false">No</option>
            {/if}
          </select>
        
        {:else}
          <div class="p-3 rounded-xl bg-red-500/10 border border-red-500/20 text-[10px] text-red-400 uppercase font-black tracking-widest">
            Unsupported field type: {field.type}
          </div>
        {/if}

        {#if disabledHint || help}
          <p class="text-[10px] text-white/30 ml-1 leading-relaxed italic">
            {disabled ? (disabledHint || help) : help}
          </p>
        {/if}
      </div>
    {/if}
  {/each}
</div>
